import type { Metadata } from "next";
import { MindStoreProvider } from "@/providers/mind-store-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <MindStoreProvider>{children}</MindStoreProvider>
      </body>
    </html>
  );
}
